baseURL: https://diegoalfaroinlondon.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Diego Alfaro
    subtitle: |-
      I hope you enjoy the content posted on this page and if have any doubt, feel free to reach out to Diego Alfaro.
    title: I am Diego Alfaro, from Peru LatAm. MFA student living in the best city of the entire world: LONDON
  blog: {}
  contact:
    address:
      - city: London, NW8 8NA
        country: United Kingdom
        street: 91 Frampton Street
        title: Flat
    buttonClear: Clear
    buttonSend: Send
    email:
      - email: diegoa.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7721 07587
        title: WhatsApp
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
  #    - icon: fa-twitter
  #      label: Twitter
  #      url: https://www.twitter.com
  #    - icon: fa-facebook
  #      label: Facebook
  #      url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/diegoalfarolego/
      - icon: fa-github
        label: GitHub
        url: https://github.com/dalfaro2020
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/diegoaal/
  image: ''
  name: Your name
  navigation:
#    button1:
#      - name: Get Started
#        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About
        url: blogs/diego-alfaro.html
      - name: realmadrid
        url: blogs/realmadrid
      - name: With the best professor in history of LBS
        url: blogs/dataanalytics
#      - name: Stocks
#        url: blogs/stocks
#      - name: Elements
#        url: elements.html
    menu: Menu
#    subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: b.jpg
        subtitle: A brief introduction
        title: About
        url: blogs/diego-alfaro.html
      - image: c.jpg
        subtitle: Real Madrid, the best team in the world
        title: Football in London
        url: blogs/realmadrid
      - image: datapunch.jpg
        subtitle: Data Analytics, a fantastic course
        title: With the best Professor in History of LBS
        url: blogs/dataanalytics
#      - image: d.jpg
#        subtitle: My pre-programme Data & Analytics assignment
#        title: Before LBS
#        url: blogs/before-lbs
#      - image: e.jpg
#        subtitle: Risk-Return Data & Analytics assignment
#        title: Stocks
#        url: blogs/stocks
  #     - image: pic05.jpg
  #      subtitle: Ipsum Dolor Sit Amet
  #      title: Consequat
  #      url: blogs/ipsum
  #    - image: pic06.jpg
  #      subtitle: Feugiat Amet Tempus
  #      title: Etiam
  #      url: blogs/ipsum
  # two:
  #   buttonText: Get Started
  #   enable: yes
  #   subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #     \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
  #     condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
  #     pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
  #     Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
  #     amet pharetra et feugiat tempus."
  #  title: Feel free to reach out 
  #  url: blogs
