baseURL: https://diegoalfaroinlondon.netlify.app/
languageCode: en-us
title: Portfolio Website of Diego
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Diego, an MFA student from Peru, LatAm. I hope you enjoy all the content and innovation posted on my webpage.
  blog: {}
  contact:
    address:
      - city: London
        country: Peru
        street: 91 Frampton Street
        title: My Flat
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: diegoa.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 7721-07587 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer: 
    copyright:
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/d.alfarolegonia
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/diegoalfarolego/
      - icon: fa-github
        label: GitHub
        url: https://github.com/dalfaro2020
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/diegoaal/
  image: ''
  name: Diego Alfaro
  navigation:
    button1:
      - name: Get Started
        url: Project/Project1
    button2:
      - name: Log In
        url: Project2
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: Project3
      - name: Elements
        url: Project4
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Now in London, UK
        title: Diego, The Warrior
        url: Projects/Project1
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "xd."
    title: Massa libero
    url: projects/project1
